### PR TITLE
update

### PR DESCRIPTION
**Pull request by melanc**
merge from origin

### CODE REVIEW

**Comment by melanc** [comment]
merge from origin

**Comment by melanc** [comment]
merge from origin

**Comment by melanc** [comment]
merge from origin

**Comment by melanc** [comment]
merge from origin

**Comment by melanc** [comment]
This pull request contains merge conflicts that must be resolved.

**Comment by fcten** [comment]
换行符的问题由于IDE导致。新增的文件似乎并无必要纳入版本控制。

**Pull request closed without merging**
